# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'pb'

require 'grpc'
require 'user_pb'

module Pb
  module User
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pb.User'

      rpc :GetUserInfo, UserRequest, UserResponse
    end

    Stub = Service.rpc_stub_class
  end
end
