# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "pb.UserRequest" do
      optional :name, :string, 1
    end
    add_message "pb.UserResponse" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :age, :int32, 3
      repeated :title, :string, 4
    end
  end
end

module Pb
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.UserRequest").msgclass
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.UserResponse").msgclass
end
